/**
 * Admin Module — Super-admin Control Plane (Phase 5 / Epic 10A-2).
 *
 * API client + hooks for `/api/v1/admin/*` endpoints.
 */

export {
  acknowledgeHealthAlert,
  createSystemAnnouncement,
  deleteSystemAnnouncement,
  fetchHealthAlerts,
  fetchHealthDashboard,
  fetchMetricHistory,
  fetchSupportData,
  getAgency,
  getOAuthClient,
  getSystemAnnouncement,
  listAgencies,
  listOAuthClients,
  listSystemAnnouncements,
  regenerateOAuthClientSecret,
  registerOAuthClient,
  revokeOAuthClient,
  suspendAgency,
  updateHealthThreshold,
  updateOAuthClient,
  updateSystemAnnouncement,
} from './api';
export {
  adminKeys,
  useAcknowledgeAlert,
  useAgencies,
  useAgency,
  useCreateSystemAnnouncement,
  useDeleteSystemAnnouncement,
  useHealthAlerts,
  useHealthDashboard,
  useMetricHistory,
  useOAuthClient,
  useOAuthClients,
  useRegenerateOAuthClientSecret,
  useRegisterOAuthClient,
  useRevokeOAuthClient,
  useSupportData,
  useSystemAnnouncement,
  useSystemAnnouncements,
  useUpdateHealthThreshold,
  useUpdateOAuthClient,
  useUpdateSystemAnnouncement,
} from './hooks';
export {
  hasMfaChallengeHandler,
  type MfaChallengeHandler,
  setMfaChallengeHandler,
} from './mfa-handler';
export type {
  AdminPaginatedResponse,
  Agency,
  AgencyDetail,
  AgencyStatus,
  CreateSystemAnnouncementRequest,
  CreateSystemAnnouncementResponse,
  CurrentMetric,
  FaultStatusCount,
  HealthDashboard,
  KnownOAuthScope,
  ListAgenciesParams,
  ListSystemAnnouncementsParams,
  MetricAlert,
  MetricDataPoint,
  MetricHistory,
  MetricStats,
  MetricStatus,
  MetricThreshold,
  OAuthClientSummary,
  RegenerateSecretResponse,
  RegisterOAuthClientRequest,
  RegisterOAuthClientResponse,
  SupportData,
  SupportDataResponse,
  SystemAnnouncement,
  SystemAnnouncementSeverity,
  TimeRange,
  UpdateOAuthClientRequest,
  UpdateSystemAnnouncementRequest,
  UpdateThresholdRequest,
} from './types';
export { KNOWN_OAUTH_SCOPES, OAUTH_SCOPE_DESCRIPTIONS } from './types';
