//! Phase 5.5 — Tenant Lifecycle & Operability.
//!
//! This crate owns the per-tenant lifecycle operations:
//!
//! * **Export** — produce a self-contained NDJSON-in-tarball snapshot of
//!   exactly one organization's data. Defense for leak #18 (encrypted
//!   per-tenant exports rather than one-blob backups).
//! * **Purge** — manifest-driven hard-delete of one organization's data
//!   across every tenant-scoped table + S3. Defense for leak #17 (CI
//!   guarantees the manifest covers every tenant table; the test
//!   `purge_completeness_tests` is the keystone there).
//! * **Restore** — admin-only reload of a previously-exported tarball
//!   into a *new* org id (never in place — defense for leak #16).
//!
//! The data plan is read from `backend/manifests/tenant-data-manifest.json`,
//! generated by `backend/scripts/check-rls-coverage.sh --emit-manifest`. The
//! manifest IS the source of truth — the same script produces it that
//! enforces RLS coverage, so a missing tenant table in the schema is also a
//! missing tenant table here.
//!
//! # Why a separate crate
//!
//! Phase 5 owns `admin-core`, which is being implemented in parallel. To
//! stay out of that branch's territory we land here as `tenant-ops` and
//! plan to merge into `admin-core` once both phases land. The public API
//! (`export_tenant`, `purge_tenant`, `restore_tenant_export`) is stable;
//! the merge is mechanical.

pub mod manifest;
pub mod purge;
pub mod export;
pub mod restore;
pub mod errors;

pub use errors::{TenantOpsError, TenantOpsResult};
pub use manifest::{TenantDataManifest, TenantTable, TableKind};
pub use purge::{purge_tenant, PurgeReport};
pub use export::{export_tenant, TenantExport};
pub use restore::{restore_tenant_export, RestoreReport};
