//! Tenant-data manifest reader.
//!
//! The single source of truth for "which tables hold per-tenant data" is
//! `backend/manifests/tenant-data-manifest.json`, generated by
//! `backend/scripts/check-rls-coverage.sh --emit-manifest`. The same script
//! enforces RLS coverage in CI, so the two never drift: if a developer adds
//! a tenant-scoped table without regenerating the manifest, both the RLS
//! coverage gate and the `purge_completeness_tests` will fail.

use crate::errors::{TenantOpsError, TenantOpsResult};
use serde::{Deserialize, Serialize};
use std::path::Path;

/// Whether a table holds its own org id, or reaches it via a parent FK.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum TableKind {
    /// Has an `organization_id` (or `org_id`) column directly.
    OwnOrg,
    /// Reaches a tenant-scoped table via a foreign key only.
    Child,
}

/// One entry in the manifest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TenantTable {
    /// Table name (unqualified, schema is always `public`).
    pub table: String,
    /// Whether the table has its own org id column or only a child link.
    pub kind: TableKind,
    /// The org-id column name on this table (`organization_id` or `org_id`),
    /// or empty string for `Child` tables.
    pub org_column: String,
}

impl TenantTable {
    /// True if this table is purgeable by a direct `WHERE org_column = $1`
    /// query — i.e. it has a real org-id column.
    pub fn is_directly_org_scoped(&self) -> bool {
        self.kind == TableKind::OwnOrg && !self.org_column.is_empty()
    }
}

/// The whole manifest.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TenantDataManifest {
    pub manifest_version: u32,
    pub generated_at: String,
    pub git_sha: String,
    pub migration_count: u32,
    pub postgres_version: String,
    pub exempt_tables: Vec<String>,
    pub tables: Vec<TenantTable>,
}

impl TenantDataManifest {
    /// Read the manifest from disk.
    pub fn load(path: impl AsRef<Path>) -> TenantOpsResult<Self> {
        let raw = std::fs::read_to_string(path.as_ref())?;
        let manifest: Self =
            serde_json::from_str(&raw).map_err(|e| TenantOpsError::ManifestParse(e.to_string()))?;
        Ok(manifest)
    }

    /// Default in-repo location.
    pub fn default_path() -> std::path::PathBuf {
        std::path::PathBuf::from("backend/manifests/tenant-data-manifest.json")
    }

    /// Read from the default repo path. Convenience for binaries / tests
    /// running with the workspace root as the CWD.
    pub fn load_default() -> TenantOpsResult<Self> {
        Self::load(Self::default_path())
    }

    /// All tables in the manifest, in the order CI emitted them. Direct
    /// `OwnOrg` tables come first; child tables follow.
    pub fn all_tables(&self) -> &[TenantTable] {
        &self.tables
    }

    /// Just the direct-`organization_id` tables — these are the ones the
    /// purge plan can hit with a one-line `DELETE WHERE org_id = $1`.
    pub fn own_org_tables(&self) -> impl Iterator<Item = &TenantTable> {
        self.tables.iter().filter(|t| t.is_directly_org_scoped())
    }

    /// Look up a table.
    pub fn find(&self, table: &str) -> Option<&TenantTable> {
        self.tables.iter().find(|t| t.table == table)
    }

    /// Number of tables.
    pub fn len(&self) -> usize {
        self.tables.len()
    }

    /// Empty manifest (defensive — would mean broken generation).
    pub fn is_empty(&self) -> bool {
        self.tables.is_empty()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_minimal_manifest_json() {
        let json = r#"{
            "manifest_version": 1,
            "generated_at": "2026-05-15T07:41:21Z",
            "git_sha": "abc123",
            "migration_count": 127,
            "postgres_version": "16.13",
            "exempt_tables": ["organizations"],
            "tables": [
                { "table": "buildings", "kind": "own_org", "org_column": "organization_id" },
                { "table": "listing_photos", "kind": "child", "org_column": "" }
            ]
        }"#;
        let m: TenantDataManifest = serde_json::from_str(json).unwrap();
        assert_eq!(m.manifest_version, 1);
        assert_eq!(m.tables.len(), 2);
        assert_eq!(m.own_org_tables().count(), 1);
        assert!(m.find("buildings").unwrap().is_directly_org_scoped());
        assert!(!m.find("listing_photos").unwrap().is_directly_org_scoped());
    }

    #[test]
    fn loads_real_manifest_if_present() {
        let path = TenantDataManifest::default_path();
        if !path.exists() {
            // Tests run from the crate dir; jump up two levels.
            let alt = std::path::PathBuf::from("../../manifests/tenant-data-manifest.json");
            if !alt.exists() {
                eprintln!("manifest not present at default or alt path; skipping");
                return;
            }
            let m = TenantDataManifest::load(&alt).expect("load manifest");
            assert!(!m.is_empty());
            return;
        }
        let m = TenantDataManifest::load_default().expect("load manifest");
        assert!(!m.is_empty());
    }
}
