/**
 * withIosBuildConfig
 *
 * Epic 85 - Story 85.2: Build Configuration by Environment (iOS).
 *
 * Background
 * ----------
 * This Expo app uses the *managed* workflow: there is no checked-in native
 * `ios/` Xcode project — it is generated by `expo prebuild` / EAS Build. The
 * per-environment runtime config (API base URL, ENVIRONMENT, etc.) is already
 * owned by `.env.<APP_ENV>` -> `app.config.ts` (dotenv -> `ios.infoPlist` +
 * `Constants.expoConfig.extra`). See app.config.ts for that mechanism.
 *
 * What was missing (this story) was the *native build-layer* counterpart:
 * iOS `.xcconfig` files that configure the Xcode build (bundle id, an APP_ENV
 * marker, API base URL, ATS posture) per environment. Hand-maintaining a
 * checked-in `ios/` project is not an option in the managed workflow, so this
 * config plugin injects the right `.xcconfig` at prebuild time — exactly the
 * same pattern as `withLegacyStoragePermissions` (which edits the generated
 * AndroidManifest.xml at prebuild).
 *
 * What this plugin does (at `expo prebuild`)
 * ------------------------------------------
 *   1. Resolves the active environment from `APP_ENV` (same precedence as
 *      app.config.ts: explicit APP_ENV, else NODE_ENV-based default).
 *   2. Reads the matching committed template under `ios/xcconfig/`:
 *        development -> Development.xcconfig
 *        staging     -> Staging.xcconfig
 *        production  -> Production.xcconfig
 *   3. Applies CI overrides: if `API_BASE_URL` is present in the environment
 *      (e.g. EAS secret for production), it replaces the template's
 *      `PPT_API_BASE_URL` so a real host lands in the native build, mirroring
 *      how app.config.ts prefers `process.env.API_BASE_URL`.
 *   4. Writes the resolved content to the generated `ios/PPTEnv.xcconfig`.
 *   5. Adds a `PBXFileReference` for that file and wires it as the
 *      `baseConfigurationReference` of every Xcode build configuration so the
 *      settings actually take effect.
 *
 * Why a custom plugin (not eas.json / Info.plist alone)
 * -----------------------------------------------------
 * eas.json `buildConfiguration` only selects Debug vs Release; it cannot inject
 * arbitrary `.xcconfig` build settings. Info.plist carries *runtime* values but
 * not *build-time* settings (bundle id resolution, ATS, build-setting markers).
 * An `.xcconfig` wired via `baseConfigurationReference` is the idiomatic Xcode
 * mechanism, and a prebuild config plugin is the only managed-workflow way to
 * introduce one reproducibly.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import { type ConfigPlugin, withDangerousMod, withXcodeProject } from '@expo/config-plugins';

/** Supported environments — mirrors app.config.ts AppEnvironment. */
export type AppEnvironment = 'development' | 'staging' | 'production';

/** Basename of the xcconfig copied into the generated `ios/` project. */
export const GENERATED_XCCONFIG_NAME = 'PPTEnv.xcconfig';

/** Per-environment committed template basenames under `ios/xcconfig/`. */
export const TEMPLATE_BY_ENV: Record<AppEnvironment, string> = {
  development: 'Development.xcconfig',
  staging: 'Staging.xcconfig',
  production: 'Production.xcconfig',
};

/**
 * Resolve the active environment. Kept in lockstep with app.config.ts
 * `getAppEnv()` so the native build layer and the JS runtime layer never
 * disagree about which environment a build is.
 */
export function resolveAppEnv(env: NodeJS.ProcessEnv = process.env): AppEnvironment {
  const raw = env.APP_ENV ?? '';
  if (raw === 'staging' || raw === 'production' || raw === 'development') {
    return raw;
  }
  return env.NODE_ENV === 'production' ? 'production' : 'development';
}

/**
 * Build the resolved xcconfig contents for `appEnv`, applying any CI override
 * of the API base URL from the environment. Pure + exported so it can be unit
 * tested without a generated `ios/` project.
 *
 * @param projectRoot  app root (where the `ios/xcconfig/` templates live)
 * @param appEnv       resolved environment
 */
export function buildXcconfigContents(projectRoot: string, appEnv: AppEnvironment): string {
  const templatePath = path.join(projectRoot, 'ios', 'xcconfig', TEMPLATE_BY_ENV[appEnv]);
  const template = fs.readFileSync(templatePath, 'utf8');

  // Runtime API URL is owned by app.config.ts (`.env.<env>` -> ios.infoPlist).
  // xcconfig no longer duplicates PPT_API_BASE_URL, so no CI override is needed here.
  return template;
}

/**
 * Writes the resolved xcconfig into the generated `ios/` directory.
 */
const withGeneratedXcconfigFile: ConfigPlugin<AppEnvironment> = (config, appEnv) =>
  withDangerousMod(config, [
    'ios',
    async (cfg) => {
      const projectRoot = cfg.modRequest.projectRoot;
      const iosRoot = cfg.modRequest.platformProjectRoot;
      const contents = buildXcconfigContents(projectRoot, appEnv);
      const dest = path.join(iosRoot, GENERATED_XCCONFIG_NAME);
      await fs.promises.writeFile(dest, contents, 'utf8');
      return cfg;
    },
  ]);

/**
 * Adds a PBXFileReference for PPTEnv.xcconfig and sets it as the
 * baseConfigurationReference of every build configuration.
 */
const withXcconfigWiredIntoProject: ConfigPlugin = (config) =>
  withXcodeProject(config, (cfg) => {
    // `cfg.modResults` is the `xcode` project instance.
    // biome-ignore lint/suspicious/noExplicitAny: xcode lib has no shipped types.
    const project = cfg.modResults as any;

    const fileRefUuid = project.generateUuid();
    const fileRef = {
      isa: 'PBXFileReference',
      lastKnownFileType: 'text.xcconfig',
      path: GENERATED_XCCONFIG_NAME,
      name: GENERATED_XCCONFIG_NAME,
      sourceTree: '"<group>"',
    };

    const fileRefSection = project.pbxFileReferenceSection();
    fileRefSection[fileRefUuid] = fileRef;
    fileRefSection[`${fileRefUuid}_comment`] = GENERATED_XCCONFIG_NAME;

    // Point every XCBuildConfiguration at the xcconfig as its base config.
    const buildConfigSection = project.pbxXCBuildConfigurationSection();
    for (const key of Object.keys(buildConfigSection)) {
      if (key.endsWith('_comment')) {
        continue;
      }
      const entry = buildConfigSection[key];
      if (entry && typeof entry === 'object' && entry.isa === 'XCBuildConfiguration') {
        entry.baseConfigurationReference = fileRefUuid;
        entry.baseConfigurationReference_comment = GENERATED_XCCONFIG_NAME;
      }
    }

    return cfg;
  });

/**
 * Public plugin: resolves APP_ENV, writes the env-specific xcconfig into the
 * generated `ios/` project, and wires it into the Xcode build configurations.
 */
const withIosBuildConfig: ConfigPlugin = (config) => {
  const appEnv = resolveAppEnv();
  let next = withGeneratedXcconfigFile(config, appEnv);
  next = withXcconfigWiredIntoProject(next);
  return next;
};

export default withIosBuildConfig;
