/**
 * Fault API module exports.
 */

// API functions
export {
  acceptAiSuggestion,
  addAttachment,
  addComment,
  addWorkNote,
  assignFault,
  confirmFault,
  createFault,
  deleteAttachment,
  deleteFault,
  getAiSuggestion,
  getFault,
  getFaultStatistics,
  getFaultTimeline,
  listAttachments,
  listFaultComments,
  listFaults,
  reopenFault,
  resolveFault,
  triageFault,
  updateFault,
} from './api';
// React Query hooks
export type { FaultStatisticsFilters } from './hooks';
export {
  faultKeys,
  useAcceptAiSuggestion,
  useAddAttachment,
  useAddComment,
  useAddWorkNote,
  useAiSuggestion,
  useAssignFault,
  useConfirmFault,
  useCreateFault,
  useDeleteAttachment,
  useDeleteFault,
  useFault,
  useFaultComments,
  useFaultStatistics,
  useFaults,
  useReopenFault,
  useRequestAiSuggestion,
  useResolveFault,
  useTriageFault,
  useUpdateFault,
} from './hooks';
// Types
export type {
  AddCommentRequest,
  AddWorkNoteRequest,
  AiSuggestion,
  AiSuggestionResponse,
  CreateFaultRequest,
  CreateFaultResponse,
  FaultAttachment,
  FaultCategory,
  FaultCategoryCount,
  FaultComment,
  FaultDetailResponse,
  FaultListQuery,
  FaultListResponse,
  FaultPriority,
  FaultPriorityCount,
  FaultStatistics,
  FaultStatus,
  FaultStatusCount,
  FaultSummary,
  FaultTimelineEntry,
  FaultWithDetails,
  ResolveFaultRequest,
  TriageFaultRequest,
  UpdateFaultRequest,
  WorkNote,
} from './types';
