pie title mobile build
    "shipped" : 18

pie title mobile redesign
    "not-started" : 18

pie title mobile api
    "partial" : 18

pie title mobile-native build
    "shipped" : 9

pie title mobile-native redesign
    "not-started" : 9

pie title mobile-native api
    "partial" : 9

pie title ppt-web build
    "shipped" : 18

pie title ppt-web redesign
    "not-started" : 18

pie title ppt-web api
    "partial" : 18

pie title reality-web build
    "shipped" : 9

pie title reality-web redesign
    "not-started" : 9

pie title reality-web api
    "partial" : 9
