pie title mobile build
    "n/a" : 12
    "shipped" : 6

pie title mobile redesign
    "n/a" : 12
    "in-progress" : 4
    "not-started" : 2

pie title mobile api
    "n/a" : 12
    "partial" : 6

pie title mobile-native build
    "n/a" : 9

pie title mobile-native redesign
    "n/a" : 9

pie title mobile-native api
    "n/a" : 9

pie title ppt-web build
    "shipped" : 13
    "planned" : 2
    "n/a" : 3

pie title ppt-web redesign
    "not-started" : 12
    "in-progress" : 3
    "n/a" : 3

pie title ppt-web api
    "partial" : 13
    "stub" : 2
    "n/a" : 3

pie title reality-web build
    "shipped" : 9

pie title reality-web redesign
    "in-progress" : 8
    "not-started" : 1

pie title reality-web api
    "partial" : 9
