pie title mobile build
    "n/a" : 12
    "shipped" : 6

pie title mobile redesign
    "n/a" : 12
    "not-started" : 6

pie title mobile api
    "n/a" : 12
    "partial" : 6

pie title ppt-web build
    "shipped" : 13
    "n/a" : 5

pie title ppt-web redesign
    "not-started" : 13
    "n/a" : 5

pie title ppt-web api
    "partial" : 13
    "n/a" : 5
