pie title mobile build
    "n/a" : 12
    "shipped" : 6
    "planned" : 2

pie title mobile redesign
    "n/a" : 12
    "in-progress" : 8

pie title mobile api
    "n/a" : 12
    "partial" : 6
    "stub" : 2

pie title ppt-web build
    "shipped" : 13
    "planned" : 5
    "n/a" : 2

pie title ppt-web redesign
    "in-progress" : 18
    "n/a" : 2

pie title ppt-web api
    "partial" : 13
    "stub" : 5
    "n/a" : 2
