pie title mobile build
    "shipped" : 18

pie title mobile redesign
    "not-started" : 18

pie title mobile api
    "partial" : 18

pie title ppt-web build
    "shipped" : 18

pie title ppt-web redesign
    "not-started" : 18

pie title ppt-web api
    "partial" : 18
