pie title mobile-native build
    "planned" : 9
    "n/a" : 8
    "in-progress" : 10

pie title mobile-native redesign
    "in-progress" : 19
    "n/a" : 8

pie title mobile-native api
    "n/a" : 15
    "stub" : 9
    "partial" : 3

pie title reality-web build
    "planned" : 4
    "in-progress" : 14
    "shipped" : 9

pie title reality-web redesign
    "in-progress" : 26
    "not-started" : 1

pie title reality-web api
    "n/a" : 7
    "partial" : 15
    "stub" : 5
